import { useState } from "react";
import { Plus } from "lucide-react";

const FAQS = [
  {
    q: "What does EmployeeAI predict?",
    a: "It predicts whether an employee is more likely to leave or stay.",
  },
  {
    q: "What data is required?",
    a: "The application uses the existing employee profile fields provided in the prediction form.",
  },
  {
    q: "Is the prediction generated by the real ML model?",
    a: "Yes. The frontend sends the employee data to the FastAPI backend.",
  },
  {
    q: "What does the probability mean?",
    a: "It represents the model's estimated probability for the leave/stay outcomes.",
  },
  {
    q: "What is the decision threshold?",
    a: "The current decision threshold is 50%.",
  },
];

function FAQItem({ q, a, isOpen, onToggle }) {
  return (
    <div className="border-b border-border-soft last:border-0">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between gap-4 py-5 text-left"
        aria-expanded={isOpen}
      >
        <span className="font-display font-medium text-[15px] text-ink-text">
          {q}
        </span>
        <Plus
          size={18}
          className={`shrink-0 text-primary transition-transform duration-300 ${
            isOpen ? "rotate-45" : ""
          }`}
        />
      </button>
      <div
        className={`grid transition-all duration-300 ease-out ${
          isOpen ? "grid-rows-[1fr] opacity-100 pb-5" : "grid-rows-[0fr] opacity-0"
        }`}
        style={{ display: "grid" }}
      >
        <div className="overflow-hidden">
          <p className="text-sm text-muted leading-relaxed">{a}</p>
        </div>
      </div>
    </div>
  );
}

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState(0);

  return (
    <section className="max-w-3xl mx-auto px-5 lg:px-8 py-20 lg:py-28">
      <div className="text-center mb-10 fade-up">
        <span className="inline-flex items-center px-3 py-1 rounded-full bg-mint-soft text-primary text-xs font-semibold uppercase tracking-wide mb-4">
          FAQ
        </span>
        <h2 className="font-display font-bold text-3xl sm:text-4xl tracking-tight text-ink-text">
          Frequently asked questions.
        </h2>
      </div>

      <div className="bg-white border border-border rounded-2xl px-6 lg:px-8">
        {FAQS.map((item, i) => (
          <FAQItem
            key={item.q}
            {...item}
            isOpen={openIndex === i}
            onToggle={() => setOpenIndex(openIndex === i ? -1 : i)}
          />
        ))}
      </div>
    </section>
  );
}
